---
- name: Include ami_config role
  hosts: ami_instances
  #strategy: debug
  become: true
  gather_facts: yes
  vars:
    - ansible_ssh_user: ec2-user
  vars_files:
    - aws_vars.yml
  roles:
    - { role: ami_config, when: ami_config is defined }
...

