---
# roles/ami-build/tasks/main.yml

- name: Subscription Manager 
  ec2_vpc_net:
    name:             "{{ aws_vpc_name }}"
    cidr_block:       "{{ aws_vpc_cidr_block }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ ec2_access_key }}"
    aws_secret_key:   "{{ ec2_secret_key }}"
    state:            "present"
  register: my_vpc

