#!/bin/bash

docker tag registry.access.redhat.com/openshift3/node:v3.4.1.10 repos.osp.example.com:5000/openshift3/node:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/metrics-deployer:v3.4.1.10 repos.osp.example.com:5000/openshift3/metrics-deployer:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/ose-docker-builder:v3.4.1.10 repos.osp.example.com:5000/openshift3/ose-docker-builder:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/ose-sti-builder:v3.4.1.10 repos.osp.example.com:5000/openshift3/ose-sti-builder:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/ose-haproxy-router:v3.4.1.10 repos.osp.example.com:5000/openshift3/ose-haproxy-router:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/ose-deployer:v3.4.1.10 repos.osp.example.com:5000/openshift3/ose-deployer:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/ose-keepalived-ipfailover:v3.4.1.10 repos.osp.example.com:5000/openshift3/ose-keepalived-ipfailover:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/ose-docker-registry:v3.4.1.10 repos.osp.example.com:5000/openshift3/ose-docker-registry:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/ose:v3.4.1.10 repos.osp.example.com:5000/openshift3/ose:v3.4.1.10
docker tag registry.access.redhat.com/openshift3/ose-pod:v3.4.1.10 repos.osp.example.com:5000/openshift3/ose-pod:v3.4.1.10

docker tag registry.access.redhat.com/openshift3/metrics-deployer:3.4.1 repos.osp.example.com:5000/openshift3/metrics-deployer:3.4.1
docker tag registry.access.redhat.com/openshift3/metrics-heapster:3.4.1 repos.osp.example.com:5000/openshift3/metrics-heapster:3.4.1
docker tag registry.access.redhat.com/openshift3/metrics-cassandra:3.4.1 repos.osp.example.com:5000/openshift3/metrics-cassandra:3.4.1
docker tag registry.access.redhat.com/openshift3/metrics-hawkular-metrics:3.4.1 repos.osp.example.com:5000/openshift3/metrics-hawkular-metrics:3.4.1

docker tag registry.access.redhat.com/rhscl/php-70-rhel7:latest repos.osp.example.com:5000/rhscl/php-70-rhel7:latest
docker tag registry.access.redhat.com/rhscl/mysql-57-rhel7:latest repos.osp.example.com:5000/rhscl/mysql-57-rhel7:latest

docker tag registry.access.redhat.com/cloudforms/cfme-openshift-memcached:latest repos.osp.example.com:5000/cloudforms/cfme-openshift-memcached:latest
docker tag registry.access.redhat.com/cloudforms/cfme-openshift-app:latest repos.osp.example.com:5000/cloudforms/cfme-openshift-app:latest
docker tag registry.access.redhat.com/cloudforms/cfme-openshift-postgresql:latest repos.osp.example.com:5000/cloudforms/cfme-openshift-postgresql:latest