---
- name: Create Lab For Students
  hosts: localhost
  gather_facts: no
  vars_files:
    - aws_vars.yml

  tasks:
    - name: Provision AWS Instances
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        key_name: "{{ aws_key_name }}"
        group: "{{ aws_sec_group }}"
        instance_type: "{{ tower_inst_type }}"
        image: "{{ tower_ami_id }}"
        wait: true
        instance_tags:
          Name: "{{ lab_name + '-tower-' + lab_user + '-' + item }}"
          lab_name: "{{ lab_name }}"
          lab_user: "{{ lab_user }}"
          lab_role: "ansible-tower"
          student_count: "{{ item }}"
        vpc_subnet_id: "{{ aws_subnet_id }}"
        zone: "{{ aws_az_1 }}"
        assign_public_ip: yes
        region: "{{ aws_region }}"
        state: present
      with_sequence: count={{ student_count }}
      register: instances_created

    - debug:
        var: instances_created
        verbosity: 2

    - name: Wait for ssh
      wait_for:
        port: 22
        host: "{{ item.instances.0.public_ip }}"
        timeout: 600
      with_items: "{{ instances_created.results }}"
