---

- name: Install pip
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - python2-pip
    - git
    - pyOpenSSL
    - python-netaddr
    - python-six
    - python2-boto3
    - python-click
    - python-httplib2

#- name: Install Tower CLI
#  pip:
#    name: "{{ item }}"
#  become: true
#  with_items:
#    - ansible-tower-cli
#    - python2-boto

- name: Update tower group
  tower_group:
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    name: AWS
    source: ec2
    credential: AWS
    inventory: "OpenShift"
    inventory_filters: "tag:student_id="{{ ec2_tag_student_id }}"
    source_vars:
      regions: "{{ aws_region }}"
      vpc_destination_variable: public_dns_name
      hostname_variable: tag_Name
    state: present
