---
- name: Add user to manage Tower
  command: >
    tower-cli user create 
      --username "{{ student_id }}"
      --password "{{ tower_password }}"
      --email "{{ student_id + '@example.org' }}"
      --is-superuser true
      --tower-host "{{ tower_host }}"
      --tower-username "{{ tower_username }}"
      --tower-password "{{ tower_password }}"

- set_fact:
    tower_username: "{{ student_id }}"

- include: auth.yml
...
